import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

function ReferralSearch() {
  const navigate = useNavigate();

  const [referralId, setReferralId] = useState("");
  const [referral, setReferral] = useState(null);
  const [error, setError] = useState("");

  const searchReferral = () => {
    setError("");
    setReferral(null);

    const savedReferral = localStorage.getItem(
      "hospitalLockerReferral"
    );

    if (!savedReferral) {
      setError(
        "No referral has been created yet. Please create a referral from the PHC Portal."
      );
      return;
    }

    const storedReferral = JSON.parse(savedReferral);

    if (
      referralId.trim().toUpperCase() ===
      storedReferral.referralId.toUpperCase()
    ) {
      setReferral(storedReferral);
    } else {
      setError(
        "Referral not found. Please check the Referral ID."
      );
    }
  };

  const accessPatient = () => {
    navigate("/hospital/patient-access", {
      state: {
        referral,
      },
    });
  };

  return (
    <div
      style={{
        minHeight: "100vh",
        backgroundColor: "#f8fafc",
        fontFamily: "Arial, sans-serif",
      }}
    >
      {/* Header */}

      <div
        style={{
          backgroundColor: "white",
          borderBottom: "1px solid #e5e7eb",
          padding: "18px 35px",
        }}
      >
        <h2
          style={{
            margin: 0,
            color: "#2563eb",
          }}
        >
          HospitalLocker AI
        </h2>

        <p
          style={{
            margin: "4px 0 0",
            color: "#64748b",
            fontSize: "13px",
          }}
        >
          Hospital Reception • Referral Management
        </p>
      </div>

      <main
        style={{
          maxWidth: "900px",
          margin: "0 auto",
          padding: "40px 25px",
        }}
      >
        <p style={{ color: "#64748b" }}>
          Hospital Portal
        </p>

        <h1
          style={{
            marginTop: 0,
            color: "#0f172a",
          }}
        >
          Search Digital Referral
        </h1>

        <p style={{ color: "#64748b" }}>
          Enter the referral ID received from the PHC.
        </p>

        {/* Search Box */}

        <div
          style={{
            backgroundColor: "white",
            border: "1px solid #e5e7eb",
            borderRadius: "12px",
            padding: "25px",
            marginTop: "25px",
          }}
        >
          <label>Referral ID</label>

          <div
            style={{
              display: "flex",
              gap: "10px",
              marginTop: "8px",
            }}
          >
            <input
              value={referralId}
              onChange={(e) =>
                setReferralId(e.target.value)
              }
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  searchReferral();
                }
              }}
              placeholder="Example: HL-REF-12345"
            />

            <button
              onClick={searchReferral}
              style={{
                padding: "12px 22px",
                border: "none",
                borderRadius: "8px",
                backgroundColor: "#2563eb",
                color: "white",
                fontWeight: "600",
                cursor: "pointer",
                whiteSpace: "nowrap",
              }}
            >
              Search
            </button>
          </div>

          <p
            style={{
              color: "#94a3b8",
              fontSize: "12px",
              marginBottom: 0,
            }}
          >
            Enter the Referral ID generated by the PHC.
          </p>
        </div>

        {/* Error */}

        {error && (
          <div
            style={{
              marginTop: "20px",
              padding: "15px",
              backgroundColor: "#fef2f2",
              border: "1px solid #fecaca",
              borderRadius: "10px",
              color: "#b91c1c",
            }}
          >
            {error}
          </div>
        )}

        {/* Referral Found */}

        {referral && (
          <div
            style={{
              marginTop: "25px",
              backgroundColor: "white",
              border: "1px solid #bbf7d0",
              borderRadius: "12px",
              padding: "25px",
            }}
          >
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
              }}
            >
              <div>
                <p
                  style={{
                    margin: 0,
                    color: "#64748b",
                    fontSize: "12px",
                  }}
                >
                  REFERRAL FOUND
                </p>

                <h2
                  style={{
                    margin: "5px 0",
                    color: "#2563eb",
                  }}
                >
                  {referral.referralId}
                </h2>
              </div>

              <span
                style={{
                  backgroundColor: "#fef3c7",
                  color: "#92400e",
                  padding: "7px 12px",
                  borderRadius: "20px",
                  fontSize: "12px",
                  fontWeight: "600",
                }}
              >
                {referral.status}
              </span>
            </div>

            {/* Patient */}

            <div
              style={{
                marginTop: "25px",
                padding: "20px",
                backgroundColor: "#f8fafc",
                borderRadius: "10px",
              }}
            >
              <h3 style={{ marginTop: 0 }}>
                Patient Information
              </h3>

              <div
                style={{
                  display: "grid",
                  gridTemplateColumns:
                    "repeat(3, 1fr)",
                  gap: "15px",
                }}
              >
                <div>
                  <small>Patient</small>
                  <strong>{referral.patientName}</strong>
                </div>

                <div>
                  <small>Patient ID</small>
                  <strong>{referral.patientId}</strong>
                </div>

                <div>
                  <small>Age / Gender</small>
                  <strong>
                    {referral.age} / {referral.gender}
                  </strong>
                </div>
              </div>
            </div>

            {/* Referral Details */}

            <div
              style={{
                marginTop: "20px",
              }}
            >
              <h3>Referral Details</h3>

              <div
                style={{
                  display: "grid",
                  gridTemplateColumns:
                    "repeat(2, 1fr)",
                  gap: "15px",
                  fontSize: "14px",
                }}
              >
                <div>
                  <small>From</small>
                  <strong>{referral.source}</strong>
                </div>

                <div>
                  <small>Receiving Hospital</small>
                  <strong>{referral.hospital}</strong>
                </div>

                <div>
                  <small>Department</small>
                  <strong>{referral.department}</strong>
                </div>

                <div>
                  <small>Priority</small>
                  <strong>{referral.priority}</strong>
                </div>

                <div
                  style={{
                    gridColumn: "1 / -1",
                  }}
                >
                  <small>Reason</small>
                  <strong>{referral.reason}</strong>
                </div>

                {referral.notes && (
                  <div
                    style={{
                      gridColumn: "1 / -1",
                    }}
                  >
                    <small>Additional Notes</small>
                    <strong>{referral.notes}</strong>
                  </div>
                )}
              </div>
            </div>

            {/* Access */}

            <button
              onClick={accessPatient}
              style={{
                width: "100%",
                marginTop: "30px",
                padding: "14px",
                border: "none",
                borderRadius: "8px",
                backgroundColor: "#16a34a",
                color: "white",
                fontWeight: "600",
                fontSize: "15px",
                cursor: "pointer",
              }}
            >
              Verify & Access Patient →
            </button>

            <div
              style={{
                marginTop: "15px",
                padding: "14px",
                backgroundColor: "#eff6ff",
                borderRadius: "8px",
                color: "#475569",
                fontSize: "12px",
              }}
            >
              <strong>Authorization Required</strong>

              <p style={{ marginBottom: 0 }}>
                Patient records should only be accessed by
                authorized healthcare personnel according to
                the applicable consent and access controls.
              </p>
            </div>
          </div>
        )}
      </main>

      <style>
        {`
          label {
            display: block;
            font-size: 14px;
            font-weight: 600;
            color: #334155;
          }

          input {
            width: 100%;
            padding: 12px;
            border: 1px solid #d1d5db;
            border-radius: 8px;
            box-sizing: border-box;
            font-size: 14px;
            outline: none;
          }

          input:focus {
            border-color: #2563eb;
          }

          small {
            display: block;
            color: #64748b;
            margin-bottom: 5px;
          }

          strong {
            color: #334155;
          }

          @media (max-width: 700px) {
            div[style*="grid-template-columns: repeat(3"] {
              grid-template-columns: 1fr !important;
            }

            div[style*="grid-template-columns: repeat(2"] {
              grid-template-columns: 1fr !important;
            }
          }
        `}
      </style>
    </div>
  );
}

export default ReferralSearch;